### ISSUE TITLE
Update dependencies

### ISSUE THREAD

**Issue by LennyLip** [FlutterFlow/flutterflow-ui#22]
Can you please update dependencies?

This related to this issue https://github.com/rive-app/rive-flutter/issues/340

To work correctly I have current overides

```
dependency_overrides:
  rive: ^0.11.12
  rive_common: ^0.4.9
  flutter_cache_manager: ^3.3.2
  sqflite: ^2.3.3
  http: ^1.2.1
```

Thank you.
